package com.example.epe2aplicacionesmoviles.service

data class Word(
    val word: String,
    val meaning: String
)

object WordList {
    val wordList = listOf(
        Word("Abnegación", "Renuncia voluntaria a intereses o deseos propios en favor de otros."),
        Word("Acrónimo", "Palabra formada por las iniciales de una expresión."),
        Word("Benigno", "Que es bueno o tiene cualidades positivas."),
        Word("Cándido", "Inocente, sin malicia ni doblez."),
        Word("Diligente", "Que pone mucho interés, esmero y rapidez en hacer algo."),
        Word("Efímero", "Que dura poco tiempo."),
        Word("Frugal", "Moderado en el comer y el beber."),
        Word("Gratuito", "Que no cuesta dinero."),
        Word("Hilaridad", "Risa ruidosa y festiva."),
        Word("Ímpetu", "Fuerza o energía con que alguien hace algo."),
        Word("Jubilo", "Alegría intensa."),
        Word("Karma", "Fuerza espiritual que deriva de los actos de una persona."),
        Word("Lúgubre", "Oscuro o sombrío que causa tristeza."),
        Word("Melancolía", "Tristeza vaga, profunda."),
        Word("Nítido", "Claro, limpio, que se distingue bien."),
        Word("Óptimo", "Que es lo mejor entre varias opciones."),
        Word("Plácido", "Tranquilo, apacible."),
        Word("Quimera", "Sueño, ilusión que se anhela sin tener fundamento."),
        Word("Resiliencia", "Capacidad para adaptarse ante situaciones adversas."),
        Word("Sagaz", "Astuto, que prevé y previene las cosas."),
        Word("Tenaz", "Persistente, que no se rinde fácilmente."),
        Word("Útil", "Que sirve para algo."),
        Word("Valeroso", "Que actúa con valor y determinación."),
        Word("Whisky", "Bebida alcohólica destilada de cereales."),
        Word("Xenofobia", "Rechazo u odio hacia los extranjeros."),
        Word("Yacer", "Estar echado o tendido."),
        Word("Zelote", "Persona extremadamente devota o fanática."),
        Word("Audaz", "Atrevido, que actúa con valentía."),
        Word("Brío", "Fuerza o energía al hacer algo."),
        Word("Conciso", "Breve y claro."),
        Word("Decoro", "Honestidad, respeto, recato."),
        Word("Empatía", "Capacidad de ponerse en el lugar del otro."),
        Word("Fervor", "Pasión intensa."),
        Word("Genuino", "Auténtico, verdadero."),
        Word("Honor", "Cualidad moral que lleva al cumplimiento del deber."),
        Word("Íntegro", "Que actúa con honestidad y rectitud."),
        Word("Justicia", "Principio moral que lleva a dar a cada uno lo que le corresponde."),
        Word("Lealtad", "Fidelidad y sinceridad."),
        Word("Misericordia", "Compasión hacia los que sufren."),
        Word("Nobleza", "Cualidad de noble, honesto y generoso."),
        Word("Obstinación", "Persistencia excesiva."),
        Word("Paciencia", "Capacidad de soportar contratiempos."),
        Word("Querencia", "Lugar donde se siente seguridad o amor."),
        Word("Reverencia", "Respeto profundo."),
        Word("Sabiduría", "Conocimiento profundo y acertado."),
        Word("Templanza", "Moderación y autocontrol."),
        Word("Unión", "Acto de unirse o juntarse."),
        Word("Virtud", "Cualidad moral positiva."),
        Word("Wolframio", "Elemento químico, también conocido como tungsteno."),
        Word("Xilófono", "Instrumento musical de percusión."),
        Word("Yunta", "Par de animales unidos para trabajar."),
        Word("Zarpar", "Partir un barco desde el puerto."),
    )
}